apiVersion: v1
kind: Service
metadata:
  name: {{ include "travel-management.fullname" . }}-frontend-svc
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  selector:
    app: travel-frontend
